server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://8.137.116.121:8432/business_db?ssl=true&sslmode=verify-full&sslrootcert=D:/java_project/springcloud-demo/server.crt
    username: business
    password: Business@123
    driver-class-name: org.postgresql.Driver
    hikari:
      ssl: true
      sslrootcert: D:/java_project/springcloud-demo/server.crt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:Eureka%402024%21Secure@8.137.116.121:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBeLongEnough12345
  expiration: 86400000

# 注册配置
auth:
  register:
    invite-code-required: false
    invite-codes: "invite2024,admin123"
